### ISSUE TITLE
Elaborate on performance claims

### ISSUE THREAD

**Issue by rcannood** [lutz-hamel/popsom#14]
The authors compare the performance of their method to the som and kohonen packages. 

- Authors claim measured speedups of 60× in comparison to som (Yan, 2016). However, according to the author's own time measurements, this speedup is closer to 15×. Can you provide more insight into how 
- Can authors also provide insight into the scalability of the algorithm for the execution time in function of input dataset size (number of observations and number of features).

**Comment by lutzhamel** [comment]
I refer to a paper with a detailed performance analysis.  I don't think it is appropriate in this 'software paper' to go into such detail.

**Comment by rcannood** [comment]
Sorry @lutzhamel, but I can't agree with you here. The JOSS guidelines ask me to verify:

> If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

The claim is that popsom is 60× faster than current SOM implementations in R, which it might be. However, based on the results you included in the manuscript, it seems like it closer to 15× than to 60×. If you'd like to convince me popsom is 60× faster, I'd be happy to take a look at these results.

**Comment by fabian-s** [comment]
See also https://github.com/lutzhamel/popsom/issues/9#issue-964151813.

In my view, the issue here is that the paper claims "Up to 60x faster than traditional single-threaded training algorithms", based on the experiments in Hamel 2018 in the first section and then provides actual benchmark times for R at the very end of the paper, which support the claims made in the text that "popsom package is about an order of magnitude faster than the som package (Yan, 2016) and almost two orders of magnitude faster than the kohonen package (Wehrens & Kruisselbrink, 2018)"

I would suggest to either 

a) resolve the partial/apparent contradiction between these two claims by making the claim  "Up to 60x faster than traditional single-threaded training algorithms" more precise -- just add a phrase summarizing which algorithm(s) exactly this was compared to in the cited paper.
or

b) foreshadow the actual R benchmark results created for this paper in the Iitroduction *instead of* referencing these earlier comparisons in Hamel 2018 that seem less relevant to the R software that is described in the paper anyways.

**Comment by lutzhamel** [comment]
Agreed, I can no longer reproduce the original numbers from (Hamel, 2018). I am creating a new set of benchmarks highlighting expected speedups and possible limitations.

**Comment by rcannood** [comment]
:+1:
