### ISSUE TITLE
Improve quality of writing

### ISSUE THREAD

**Issue by rcannood** [lutz-hamel/popsom#17]
Paragraphs should consist of full sentences. Partial sentences are used when referring to pieces of code or when citing articles.

Example of incomplete sentence due to code block:

> This is easily verified with a scatter plot matrix of the iris dataset using
> -code block-
> and shown in Figure 2.

Example of incomplete sentence due to citation:

> A number of R-packages exist that implement self-organizing maps including (Wehrens & Kruisselbrink, 2018) and (Yan, 2016).

If you omit everything between parentheses, the sentence that remains is incomplete:

> A number of R-packages exist that implement self-organizing maps including and.

**Comment by lutzhamel** [comment]
I don't understand what is wrong with the first problem raised in this issue; in software papers references to code are considered to be part of the prose.  For the second problem, it is standard practice to have citations to be part of the prose in technical publications.

**Comment by fabian-s** [comment]
In my view, the first part is fine as is.

For the second part, you should use references without parentheses since these are the objects of your sentence, i.e., plz change it to "A number of R-packages exist that implement self-organizing maps including Wehrens & Kruisselbrink (2018) and Yan (2016)." This is a purely cosmetic change and should be very easy to achieve.

**Comment by lutzhamel** [comment]
I do not know how to control whedon's formatting of citations so I hope I achieved the same thing by rewriting the sentence slightly.

**Comment by rcannood** [comment]
[This link](https://pandoc.org/MANUAL.html#citations-in-note-styles) might be what you need to drop the parentheses.
