### ISSUE TITLE
S3 generics get masked

### ISSUE THREAD

**Issue by HerrMo** [lutz-hamel/popsom#7]
Functions `popsom::summary`, `popsom::predict` and `popsom::fitted` mask S3 generics.

This is very inconvenient as it breaks method dispatch for objects of other classes when `popsom` is loaded. 
Appropriate S3 methods should therefore be implemented.

With this in mind, I also suggest to move the `starburst` functionality into a S3 plot method and to add a S3 print method.

**Comment by lutzhamel** [comment]
@HerrMo I had S3 interfaces implemented for R3.x and they worked beautifully.  But when R4.x was released the S3 interfaces stopped working.  There was no documentation on what changed from R3.x -> R4.x that would make S3 interfaces break.  I wanted POPSOM to work on both versions and therefore took the S3 interfaces out. 

If you have any insights on what needs to happen for R4.x to implement S3 interfaces or what changed from R3.x to R4.x that would be greatly appreciated.  Otherwise I am afraid I only have two other options: (a) leave it as is or (b) rename the functions so they don't interfere with other S3 functions.  This package needs to be compatible with both R3.x and R4.x because a lot of Unix based systems still have R3.x as their default installation.

**Comment by lutzhamel** [comment]
I decided to sidestep the whole S3 issue by renaming the functions in the interface.  As far as I can tell there are now conflicts at this point.

**Comment by fabian-s** [comment]
@lutzhamel 
the last commit to this repo was 20 days ago -- please push the changes you made to close this issues so we can verify.
